CREATE TABLE IF NOT EXISTS agents (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL CHECK(type IN ('cli','api','local')),
  role TEXT NOT NULL,
  score INTEGER DEFAULT 50 CHECK(score BETWEEN 1 AND 100),
  model TEXT,
  command TEXT,
  args_json TEXT DEFAULT '[]',
  endpoint TEXT,
  api_key_ref TEXT,
  capabilities_json TEXT NOT NULL DEFAULT '[]',
  permissions_json TEXT DEFAULT '{}',
  persona_json TEXT DEFAULT '{}',
  sandbox_json TEXT DEFAULT '{}',
  concurrency INTEGER DEFAULT 4,
  rate_limit_rpm INTEGER DEFAULT 20,
  cost TEXT DEFAULT 'free' CHECK(cost IN ('free','paid')),
  enabled INTEGER DEFAULT 1,
  status TEXT DEFAULT 'offline',
  last_heartbeat TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  removed_at TEXT
);
