/**
 * NCO Dynamic Skill Engine — 런타임 스킬 자동 생성·등록·실행
 *
 * 미쏘스 능가 핵심 기능:
 *   - 자연어 설명 → 파이프라인 자동 생성
 *   - 반복 패턴 감지 → 스킬 자동 제안
 *   - 성능 기반 파이프라인 자동 최적화
 *   - DB 저장 → conductor가 자동 참조
 */

import { getDb } from '../storage/database.js';
import { qualityGate, type TaskType } from './quality-gate.js';
import { smartRouter } from './smart-router.js';
import { createLogger } from '../utils/logger.js';

const log = createLogger('dynamic-skill-engine');

export interface SkillPipelineStep {
  step: number;
  agentId: string;
  promptTemplate: string;  // {{prompt}}, {{context}}, {{prev_output}} 치환자 사용
  qualityThreshold?: number;
}

export interface DynamicSkill {
  id: string;
  name: string;
  description: string;
  triggerKeywords: string[];
  pipeline: SkillPipelineStep[];
  qualityThreshold: number;
  usageCount: number;
  avgQuality: number;
  isActive: boolean;
  autoGenerated: boolean;
  createdAt: string;
}

// ── 자동 파이프라인 생성 규칙 ─────────────────────────────────────────
const PIPELINE_TEMPLATES: Array<{
  pattern: RegExp;
  taskType: TaskType;
  pipeline: Omit<SkillPipelineStep, 'step'>[];
}> = [
  {
    pattern: /코드.*구현|implement|build|개발/i,
    taskType: 'code',
    pipeline: [
      { agentId: 'opencode', promptTemplate: '[설계] {{prompt}}의 아키텍처와 구조를 설계하라.' },
      { agentId: 'codex',    promptTemplate: '[구현] {{prompt}}\n\n[설계]\n{{prev_output}}', qualityThreshold: 65 },
      { agentId: 'cursor-agent', promptTemplate: '[리뷰] 다음 구현을 코드 품질·보안 관점에서 리뷰하라:\n{{prev_output}}' },
    ],
  },
  {
    pattern: /분석|analyze|조사|research/i,
    taskType: 'research',
    pipeline: [
      { agentId: 'copilot',  promptTemplate: '[리서치] {{prompt}}에 대해 조사하라.' },
      { agentId: 'nvidia',   promptTemplate: '[분석] 다음 리서치 결과를 심층 분석하라:\n{{prev_output}}\n\n원래 질문: {{prompt}}' },
    ],
  },
  {
    pattern: /UI|UX|화면|디자인|design/i,
    taskType: 'ui',
    pipeline: [
      { agentId: 'agy',   promptTemplate: '[UI 설계] {{prompt}}의 UI/UX를 설계하라.' },
      { agentId: 'codex',    promptTemplate: '[UI 구현] {{prompt}}\n\n[설계]\n{{prev_output}}', qualityThreshold: 60 },
    ],
  },
  {
    pattern: /검증|verify|test|테스트/i,
    taskType: 'verify',
    pipeline: [
      { agentId: 'cursor-agent', promptTemplate: '[검증] {{prompt}}를 검증하라.' },
      { agentId: 'cursor-agent', promptTemplate: '[보안 검증] {{prompt}}\n\n[1차 검증]\n{{prev_output}}' },
    ],
  },
];

class DynamicSkillEngine {
  /**
   * 자연어 설명으로 스킬을 자동 생성하고 DB에 등록한다.
   */
  async generateSkill(params: {
    name: string;
    description: string;
    triggerKeywords?: string[];
    customPipeline?: SkillPipelineStep[];
  }): Promise<DynamicSkill> {
    const db = getDb();
    const id = `skill_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;

    // 파이프라인 자동 결정
    let pipeline: SkillPipelineStep[];
    if (params.customPipeline && params.customPipeline.length > 0) {
      pipeline = params.customPipeline;
    } else {
      pipeline = this.inferPipeline(params.description);
    }

    // 트리거 키워드 자동 추출
    const keywords = params.triggerKeywords ?? this.extractTriggerKeywords(params.description);

    const skill: DynamicSkill = {
      id,
      name: params.name,
      description: params.description,
      triggerKeywords: keywords,
      pipeline,
      qualityThreshold: 60,
      usageCount: 0,
      avgQuality: 0,
      isActive: true,
      autoGenerated: true,
      createdAt: new Date().toISOString(),
    };

    db.prepare(
      `INSERT OR REPLACE INTO dynamic_skills
       (id, name, description, trigger_keywords, pipeline, quality_threshold, is_active, auto_generated)
       VALUES (?, ?, ?, ?, ?, ?, 1, 1)`
    ).run(id, skill.name, skill.description, JSON.stringify(keywords), JSON.stringify(pipeline), skill.qualityThreshold);

    log.info({ id, name: skill.name, steps: pipeline.length, keywords }, 'Dynamic skill generated');
    return skill;
  }

  /**
   * 등록된 스킬을 실행한다.
   * executor: (agentId, prompt) => Promise<string>
   */
  async executeSkill(
    skillId: string,
    userPrompt: string,
    executor: (agentId: string, prompt: string) => Promise<string>,
  ): Promise<{ output: string; quality: number; steps: number }> {
    const db = getDb();
    const row = db.prepare(`SELECT * FROM dynamic_skills WHERE id=? AND is_active=1`).get(skillId) as any;
    if (!row) throw new Error(`Skill not found: ${skillId}`);

    const pipeline: SkillPipelineStep[] = JSON.parse(row.pipeline ?? '[]');
    let context = '';
    let prevOutput = '';
    let finalOutput = '';

    for (const step of pipeline) {
      const prompt = step.promptTemplate
        .replace(/\{\{prompt\}\}/g, userPrompt)
        .replace(/\{\{context\}\}/g, context)
        .replace(/\{\{prev_output\}\}/g, prevOutput);

      try {
        const output = await executor(step.agentId, prompt);
        const quality = qualityGate.evaluate(output, prompt, 'general', step.qualityThreshold ?? 55);

        prevOutput = output;
        context += `\n## Step ${step.step} (${step.agentId})\n${output.slice(0, 500)}`;
        finalOutput = output;
      } catch (e: any) {
        log.warn({ step: step.step, agentId: step.agentId, err: e.message }, 'Skill step failed');
        finalOutput = prevOutput || `[Step ${step.step} failed] ${e.message}`;
      }
    }

    // 사용 카운터 갱신
    db.prepare(`UPDATE dynamic_skills SET usage_count=usage_count+1 WHERE id=?`).run(skillId);

    const finalQuality = qualityGate.evaluate(finalOutput, userPrompt).score;
    return { output: finalOutput, quality: finalQuality, steps: pipeline.length };
  }

  /**
   * 프롬프트에 매칭되는 스킬 검색 (conductor 통합용)
   */
  findMatchingSkill(prompt: string): DynamicSkill | null {
    const db = getDb();
    const skills = db.prepare(
      `SELECT * FROM dynamic_skills WHERE is_active=1 ORDER BY usage_count DESC`
    ).all() as any[];

    for (const skill of skills) {
      const keywords: string[] = JSON.parse(skill.trigger_keywords ?? '[]');
      if (keywords.some(kw => prompt.toLowerCase().includes(kw.toLowerCase()))) {
        return {
          id: skill.id,
          name: skill.name,
          description: skill.description,
          triggerKeywords: keywords,
          pipeline: JSON.parse(skill.pipeline ?? '[]'),
          qualityThreshold: skill.quality_threshold,
          usageCount: skill.usage_count,
          avgQuality: skill.avg_quality,
          isActive: skill.is_active === 1,
          autoGenerated: skill.auto_generated === 1,
          createdAt: skill.created_at,
        };
      }
    }
    return null;
  }

  listSkills(): DynamicSkill[] {
    const db = getDb();
    const rows = db.prepare(`SELECT * FROM dynamic_skills WHERE is_active=1 ORDER BY usage_count DESC`).all() as any[];
    return rows.map(r => ({
      id: r.id, name: r.name, description: r.description,
      triggerKeywords: JSON.parse(r.trigger_keywords ?? '[]'),
      pipeline: JSON.parse(r.pipeline ?? '[]'),
      qualityThreshold: r.quality_threshold,
      usageCount: r.usage_count, avgQuality: r.avg_quality,
      isActive: r.is_active === 1, autoGenerated: r.auto_generated === 1,
      createdAt: r.created_at,
    }));
  }

  private inferPipeline(description: string): SkillPipelineStep[] {
    for (const tmpl of PIPELINE_TEMPLATES) {
      if (tmpl.pattern.test(description)) {
        return tmpl.pipeline.map((s, i) => ({ ...s, step: i + 1 }));
      }
    }
    // 기본: 단일 codex 스텝
    return [{ step: 1, agentId: 'codex', promptTemplate: '{{prompt}}', qualityThreshold: 55 }];
  }

  private extractTriggerKeywords(description: string): string[] {
    const words = description
      .replace(/[^\w가-힣\s]/g, ' ')
      .split(/\s+/)
      .filter(w => w.length > 2)
      .slice(0, 8);
    return [...new Set(words)];
  }
}

export const dynamicSkillEngine = new DynamicSkillEngine();
